# Generated by Django 3.2.7 on 2021-09-12 14:47

from django.db import migrations, models
import predictAPI.models


class Migration(migrations.Migration):

    dependencies = [
        ('predictAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_settings',
            name='custom_settings',
            field=models.JSONField(default=predictAPI.models.default_settings),
        ),
    ]
