# Generated by Django 3.2.7 on 2021-09-12 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictAPI', '0002_alter_user_settings_custom_settings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user_settings',
            new_name='user_setting',
        ),
    ]
