# Generated by Django 3.2.7 on 2021-09-12 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictAPI', '0003_rename_user_settings_user_setting'),
    ]

    operations = [
        migrations.CreateModel(
            name='TLE_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='satellite_name', max_length=80)),
                ('line1', models.CharField(default='', max_length=80)),
                ('line2', models.CharField(default='', max_length=80)),
            ],
        ),
    ]
