# Generated by Django 3.2.7 on 2021-09-12 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictAPI', '0004_tle_db'),
    ]

    operations = [
        migrations.AddField(
            model_name='tle_db',
            name='id_number',
            field=models.CharField(default='', max_length=80),
        ),
    ]
